# Generated by Django 4.1.7 on 2023-04-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(help_text='Имя клиента', max_length=50)),
                ('amount_of_purchases', models.IntegerField(default=0, help_text='Сумма покупок')),
                ('cust_balance', models.IntegerField(help_text='На счету')),
                ('cust_ceiling', models.IntegerField(help_text='Лимит кредита')),
                ('cust_debt', models.IntegerField(help_text='Долг')),
                ('comment', models.TextField(help_text='Комментарий', max_length=1024)),
            ],
            options={
                'verbose_name': 'Клиенты',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=255)),
                ('prod_cost', models.IntegerField()),
                ('prod_amount', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Продукты',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
